# Generated by Django 6.0.3 on 2026-04-30 02:18

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("quantidade_estoque", models.PositiveIntegerField(default=0)),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("Vermelho", "Vermelho"),
                            ("Azul", "Azul"),
                            ("Verde", "Verde"),
                            ("Amarelo", "Amarelo"),
                            ("Preto", "Preto"),
                            ("Branco", "Branco"),
                            ("Rosa", "Rosa"),
                            ("Roxo", "Roxo"),
                            ("Laranja", "Laranja"),
                            ("Cinza", "Cinza"),
                            ("Marrom", "Marrom"),
                            ("Outro", "Outro"),
                        ],
                        default="Branco",
                        max_length=20,
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                            ("U", "Único"),
                        ],
                        default="M",
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("lancamentos", "Lançamentos"),
                            ("promocoes", "Promoções"),
                            ("conjuntos", "Conjuntos"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=20,
                    ),
                ),
                (
                    "imagem",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="imagem"
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EnderecoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=50)),
                ("bairro", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=2)),
                ("principal", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Endereços de Entrega",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aguardando_aprovacao", "Aguardando Aprovação"),
                            ("aprovado", "Aprovado"),
                            ("processando", "Processando"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovado", "Aprovado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "status_entrega",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("preparando", "Preparando"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("retirado", "Retirado"),
                        ],
                        default="aguardando",
                        max_length=20,
                    ),
                ),
                (
                    "metodo_pagamento",
                    models.CharField(
                        choices=[("pix", "PIX"), ("cartao", "Cartão de Crédito")],
                        default="pix",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[
                            ("retirada", "Retirada na Loja"),
                            ("entrega", "Entrega"),
                        ],
                        default="retirada",
                        max_length=20,
                    ),
                ),
                (
                    "frete",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "id_mercado_pago",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("qr_code", models.TextField(blank=True, null=True)),
                ("qr_code_base64", models.TextField(blank=True, null=True)),
                (
                    "numero_cartao",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "validade_cartao",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "nome_cartao",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "endereco_entrega",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendas.enderecoentrega",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "cor_selecionada",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tamanho_selecionado",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_pedido",
                        to="vendas.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendas.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarrinhoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "cor_selecionada",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tamanho_selecionado",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "imagem_selecionada",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="imagem"
                    ),
                ),
                ("data_adicionado", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vendas.produto"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "data_venda",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data da Venda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vendas.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "ordering": ["-data_venda"],
            },
        ),
    ]
