# Generated by Django 6.0.3 on 2026-04-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_auto_20260430_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status_entrega",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando"),
                    ("preparando", "Preparando"),
                    ("enviado", "Enviado"),
                    ("entregue", "Entregue"),
                    ("retirado", "Retirado"),
                ],
                default="aguardando",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
