# Generated by Django 5.1.7 on 2026-07-14 18:01

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_alter_pedido_status_entrega_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinhoitem",
            name="cor_selecionada",
        ),
        
        migrations.RemoveField(
            model_name="carrinhoitem",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="carrinhoitem",
            name="tamanho_selecionado",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="cor_selecionada",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="itempedido",
            name="tamanho_selecionado",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="cor",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="preco",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="quantidade_estoque",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tamanho",
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de telefone inválido",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="CPF"
                    ),
                ),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
        migrations.CreateModel(
            name="ProdutoVariacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        choices=[
                            ("Vermelho", "Vermelho"),
                            ("Azul", "Azul"),
                            ("Verde", "Verde"),
                            ("Amarelo", "Amarelo"),
                            ("Preto", "Preto"),
                            ("Branco", "Branco"),
                            ("Rosa", "Rosa"),
                            ("Roxo", "Roxo"),
                            ("Laranja", "Laranja"),
                            ("Cinza", "Cinza"),
                            ("Marrom", "Marrom"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tamanho",
                    models.CharField(
                        choices=[
                            ("PP", "PP"),
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                            ("U", "Único"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("quantidade_estoque", models.PositiveIntegerField(default=0)),
                (
                    "imagem",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="imagem"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variacoes",
                        to="vendas.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["cor", "tamanho"],
                "unique_together": {("produto", "cor", "tamanho")},
            },
        ),
        migrations.AddField(
            model_name="carrinhoitem",
            name="variacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendas.produtovariacao",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itempedido",
            name="variacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendas.produtovariacao",
            ),
            preserve_default=False,
        ),
    ]
