# Generated by Django 5.1.7 on 2026-07-14 18:16
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('vendas', '0004_remove_carrinhoitem_cor_selecionada_and_more'),
    ]

    operations = [
        # Migração vazia para resolver conflitos
    ]