# Generated by Django 5.1.7 on 2026-09-30 21:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0006_remove_carrinhoitem_imagem_selecionada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venda",
            options={},
        ),
        migrations.RemoveField(
            model_name="venda",
            name="data_venda",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="total",
        ),
        migrations.AddField(
            model_name="venda",
            name="data_criacao",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("pix", "Pix"),
                    ("cartao", "Cartão"),
                    ("dinheiro", "Dinheiro"),
                    ("transferencia", "Transferência"),
                ],
                default="pix",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="variacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendas.produtovariacao",
            ),
        ),
        migrations.AlterField(
            model_name="carrinhoitem",
            name="variacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vendas.produtovariacao",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("lancamentos", "Lançamentos"),
                    ("promocoes", "Promoções"),
                    ("conjuntos", "Conjuntos"),
                    ("destaque", "Destaque"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="preco_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="venda",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vendas.produto"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="quantidade",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="venda",
            name="status",
            field=models.CharField(
                choices=[
                    ("concluida", "Concluída"),
                    ("pendente", "Pendente"),
                    ("cancelada", "Cancelada"),
                ],
                default="concluida",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ImagemVariacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="imagem"
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "variacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens_adicionais",
                        to="vendas.produtovariacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem Adicional",
                "verbose_name_plural": "Imagens Adicionais",
                "ordering": ["ordem"],
            },
        ),
    ]
