# Generated by Django 5.1.7 on 2026-07-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_fix_migration_final"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrinhoitem",
            name="imagem_selecionada",
        ),
    ]
